apiVersion: zone.crossplane.io/v1alpha1
kind: Zone
metadata:
  annotations:
    meta.upbound.io/example-id: zone/v1alpha1/zone
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    ttl: 600
    zone: terraform.example.io
